# Generated by Django 4.1.5 on 2023-02-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='description',
            field=models.CharField(max_length=4096),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='description',
            field=models.CharField(max_length=8192),
        ),
    ]
