# Generated by Django 4.1.5 on 2023-02-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_alter_cities_description_alter_landmarks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarks',
            name='latitude',
            field=models.FloatField(default=48.403841),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landmarks',
            name='longitude',
            field=models.FloatField(default=48.403841),
            preserve_default=False,
        ),
    ]
