# Generated by Django 4.1.5 on 2023-03-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0003_landmarks_latitude_landmarks_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmarks',
            name='image',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='landmarks',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
