# Generated by Django 4.1.5 on 2023-04-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0004_landmarks_image_alter_landmarks_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSuggestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('city_id', models.IntegerField()),
                ('message', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
